# Generated by Django 4.0.3 on 2022-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_intro',
            field=models.TextField(default='', max_length=500, unique=True, verbose_name='Introduction'),
        ),
    ]
